-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Drop existing tables if they exist (to start fresh)
DROP TABLE IF EXISTS blog_post CASCADE;
DROP TABLE IF EXISTS website_data CASCADE;

-- Create tables
CREATE TABLE website_data (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  host_name TEXT NOT NULL UNIQUE,
  website_name TEXT NOT NULL,
  topic TEXT NOT NULL,
  about_us TEXT NOT NULL,
  contact_us TEXT NOT NULL,
  frontpage_hero_title TEXT,
  frontpage_hero_text TEXT,
  frontpage_outro_text TEXT,
  template_header INTEGER NOT NULL CHECK (template_header BETWEEN 1 AND 5),
  template_footer INTEGER NOT NULL CHECK (template_footer BETWEEN 1 AND 5),
  template_blog_post INTEGER NOT NULL CHECK (template_blog_post BETWEEN 1 AND 5),
  template_page INTEGER NOT NULL CHECK (template_page BETWEEN 1 AND 5),
  template_front_page INTEGER NOT NULL CHECK (template_front_page BETWEEN 1 AND 5),
  primary_color TEXT NOT NULL,
  secondary_color TEXT NOT NULL,
  accent_color TEXT NOT NULL,
  background_color TEXT DEFAULT '#ffffff',
  text_color TEXT DEFAULT '#000000',
  font_heading TEXT DEFAULT 'serif',
  font_body TEXT DEFAULT 'sans-serif',
  container_width TEXT DEFAULT 'container',
  border_radius TEXT DEFAULT 'rounded-lg',
  logo_url TEXT,
  favicon_url TEXT,
  meta_description TEXT,
  social_twitter TEXT,
  social_facebook TEXT,
  social_instagram TEXT,
  social_linkedin TEXT,
  -- Component flags
  show_breadcrumbs BOOLEAN DEFAULT true,
  show_related_posts BOOLEAN DEFAULT true,
  show_search_bar BOOLEAN DEFAULT true,
  show_share_buttons BOOLEAN DEFAULT true,
  show_table_of_contents BOOLEAN DEFAULT true,
  show_author_box BOOLEAN DEFAULT true,
  show_tags_display BOOLEAN DEFAULT true,
  show_reading_time BOOLEAN DEFAULT true,
  show_post_navigation BOOLEAN DEFAULT true,
  show_reading_progress_bar BOOLEAN DEFAULT true
);

CREATE TABLE blog_post (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  website_id UUID NOT NULL REFERENCES website_data(id) ON DELETE CASCADE,
  slug TEXT NOT NULL,
  title TEXT NOT NULL,
  excerpt TEXT NOT NULL,
  content TEXT NOT NULL,
  image_url TEXT,
  author_name TEXT NOT NULL,
  author_avatar TEXT,
  published BOOLEAN DEFAULT false,
  published_at TIMESTAMP WITH TIME ZONE,
  tags TEXT[],
  meta_title TEXT,
  meta_description TEXT,
  UNIQUE(website_id, slug)
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_blog_post_website_id ON blog_post(website_id);
CREATE INDEX IF NOT EXISTS idx_blog_post_slug ON blog_post(slug);
CREATE INDEX IF NOT EXISTS idx_blog_post_published ON blog_post(published);

-- Insert dummy website data
INSERT INTO website_data (
  host_name,
  website_name,
  topic,
  about_us,
  contact_us,
  frontpage_hero_title,
  frontpage_hero_text,
  frontpage_outro_text,
  template_header,
  template_footer,
  template_blog_post,
  template_page,
  template_front_page,
  primary_color,
  secondary_color,
  accent_color,
  background_color,
  text_color,
  font_heading,
  font_body,
  container_width,
  border_radius,
  logo_url,
  favicon_url,
  meta_description,
  social_twitter,
  social_facebook,
  social_instagram,
  social_linkedin,
  show_breadcrumbs,
  show_related_posts,
  show_search_bar,
  show_share_buttons,
  show_table_of_contents,
  show_author_box,
  show_tags_display,
  show_reading_time,
  show_post_navigation,
  show_reading_progress_bar
) VALUES
(
  'localhost',
  'TechInsights',
  'Technology, AI, and Innovation',
  '<p>Welcome to TechInsights, your premier destination for cutting-edge technology news and analysis. Founded in 2024, we are passionate about exploring the intersection of technology and human progress.</p><p>Our team of expert writers and analysts brings you in-depth coverage of AI, software development, cybersecurity, and emerging technologies. We believe in making complex technical topics accessible to everyone.</p><p>Our mission is to empower readers with knowledge that helps them navigate the rapidly evolving tech landscape.</p>',
  '<p>We''d love to hear from you! Whether you have questions, feedback, or partnership opportunities, feel free to reach out.</p><p><strong>Email:</strong> contact@techinsights.com</p><p><strong>Address:</strong> 123 Innovation Drive, Silicon Valley, CA 94025</p><p><strong>Phone:</strong> (555) 123-4567</p><p>For press inquiries, please email: press@techinsights.com</p>',
  'Exploring the Future of Technology',
  'Dive deep into the latest tech trends, AI breakthroughs, and digital innovations shaping our world. Our expert analysis helps you stay ahead in the rapidly evolving technology landscape.',
  '<p>Join thousands of tech enthusiasts who trust TechInsights for their daily dose of innovation. Subscribe to our newsletter and never miss a breakthrough.</p>',
  1,
  1,
  1,
  1,
  1,
  '#2563eb',
  '#e0e7ff',
  '#7c3aed',
  '#ffffff',
  '#1f2937',
  'sans-serif',
  'sans-serif',
  'max-w-7xl',
  'rounded-lg',
  'https://via.placeholder.com/200x200/2563eb/ffffff?text=TI',
  'https://via.placeholder.com/32x32/2563eb/ffffff?text=T',
  'Your premier destination for technology news, AI insights, and innovation analysis',
  'https://twitter.com/techinsights',
  'https://facebook.com/techinsights',
  'https://instagram.com/techinsights',
  'https://linkedin.com/company/techinsights',
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true
),
(
  'localhost:3000',
  'TechInsights',
  'Technology, AI, and Innovation',
  '<p>Welcome to TechInsights, your premier destination for cutting-edge technology news and analysis. Founded in 2024, we are passionate about exploring the intersection of technology and human progress.</p><p>Our team of expert writers and analysts brings you in-depth coverage of AI, software development, cybersecurity, and emerging technologies. We believe in making complex technical topics accessible to everyone.</p><p>Our mission is to empower readers with knowledge that helps them navigate the rapidly evolving tech landscape.</p>',
  '<p>We''d love to hear from you! Whether you have questions, feedback, or partnership opportunities, feel free to reach out.</p><p><strong>Email:</strong> contact@techinsights.com</p><p><strong>Address:</strong> 123 Innovation Drive, Silicon Valley, CA 94025</p><p><strong>Phone:</strong> (555) 123-4567</p><p>For press inquiries, please email: press@techinsights.com</p>',
  'TechInsights',
  'Where innovation meets insight. Discover in-depth analysis, expert opinions, and the stories behind tomorrow''s technology.',
  '<p>Stay informed. Stay ahead. Your journey into the future of technology starts here.</p>',
  2,
  2,
  3,
  2,
  2,
  '#2563eb',
  '#f8fafc',
  '#7c3aed',
  '#f1f5f9',
  '#0f172a',
  'serif',
  'sans-serif',
  'max-w-6xl',
  'rounded-xl',
  'https://via.placeholder.com/200x200/2563eb/ffffff?text=TI',
  'https://via.placeholder.com/32x32/2563eb/ffffff?text=T',
  'Your premier destination for technology news, AI insights, and innovation analysis',
  'https://twitter.com/techinsights',
  'https://facebook.com/techinsights',
  'https://instagram.com/techinsights',
  'https://linkedin.com/company/techinsights',
  false,
  true,
  false,
  true,
  false,
  true,
  true,
  true,
  false,
  true
),
(
  'foodie.example.com',
  'The Foodie Chronicles',
  'Recipes, Restaurants, and Culinary Adventures',
  '<p>The Foodie Chronicles is your gateway to culinary excellence. We are a team of passionate food lovers, chefs, and critics dedicated to sharing the joy of great food.</p><p>From family recipes passed down through generations to the latest restaurant openings, we cover it all. Our reviews are honest, our recipes are tested, and our passion for food is infectious.</p><p>Join us on this delicious journey as we explore flavors from around the world.</p>',
  '<p>Got a recipe to share? A restaurant we should try? We want to hear from you!</p><p><strong>Email:</strong> hello@foodiechronicles.com</p><p><strong>Recipe Submissions:</strong> recipes@foodiechronicles.com</p><p><strong>Advertising:</strong> ads@foodiechronicles.com</p><p>Follow us on social media for daily food inspiration!</p>',
  'Savor Every Moment',
  'From home kitchens to Michelin stars, we celebrate the art of cooking and the joy of eating. Discover recipes that tell stories and restaurants that create memories.',
  '<p>Every meal is an adventure. Let''s explore together. Follow us for daily recipes, restaurant finds, and culinary inspiration that will make your taste buds dance.</p>',
  3,
  3,
  2,
  3,
  3,
  '#dc2626',
  '#fef2f2',
  '#f59e0b',
  '#fffbeb',
  '#7c2d12',
  'cursive',
  'sans-serif',
  'max-w-5xl',
  'rounded-2xl',
  'https://via.placeholder.com/200x200/dc2626/ffffff?text=FC',
  'https://via.placeholder.com/32x32/dc2626/ffffff?text=F',
  'Discover amazing recipes, restaurant reviews, and culinary adventures from around the world',
  'https://twitter.com/foodiechronicles',
  'https://facebook.com/foodiechronicles',
  'https://instagram.com/foodiechronicles',
  NULL,
  true,
  false,
  true,
  true,
  true,
  false,
  true,
  false,
  true,
  false
),
(
  'travel.example.com',
  'Wanderlust Diaries',
  'Travel Guides, Tips, and Adventures',
  '<p>Wanderlust Diaries was born from a simple idea: everyone deserves to explore the world. We are travelers, adventurers, and storytellers who believe that travel changes lives.</p><p>Our comprehensive guides cover destinations from bustling cities to remote islands. We share budget tips, luxury experiences, and everything in between.</p><p>Whether you''re planning your next vacation or just dreaming of far-off places, we''re here to inspire your journey.</p>',
  '<p>Planning a trip? Need travel advice? Want to share your story? Let''s connect!</p><p><strong>Email:</strong> info@wanderlustdiaries.com</p><p><strong>Collaborations:</strong> partner@wanderlustdiaries.com</p><p><strong>Instagram:</strong> @wanderlustdiaries - Tag us in your travel photos!</p><p>We''re always looking for guest writers and travel photographers.</p>',
  'Adventure Awaits',
  'Pack your bags and feed your wanderlust. Discover hidden gems, travel hacks, and inspiring stories from every corner of the globe. Your next adventure starts here.',
  '<p>The world is calling. Will you answer? Join our community of adventurers and start planning your next unforgettable journey today.</p>',
  4,
  4,
  4,
  4,
  4,
  '#0891b2',
  '#ecfeff',
  '#06b6d4',
  '#ffffff',
  '#164e63',
  'display',
  'sans-serif',
  'max-w-7xl',
  'rounded-md',
  'https://via.placeholder.com/200x200/0891b2/ffffff?text=WD',
  'https://via.placeholder.com/32x32/0891b2/ffffff?text=W',
  'Explore the world with our travel guides, tips, and inspiring stories from globe-trotters',
  'https://twitter.com/wanderlustdiaries',
  'https://facebook.com/wanderlustdiaries',
  'https://instagram.com/wanderlustdiaries',
  NULL,
  true,
  true,
  true,
  false,
  true,
  true,
  false,
  true,
  true,
  true
),
(
  'wellness.example.com',
  'Mindful Living',
  'Health, Wellness, and Mental Health',
  '<p>Mindful Living is dedicated to helping you achieve balance in body, mind, and spirit. We believe that true wellness comes from within and requires a holistic approach.</p><p>Our content covers fitness, nutrition, mental health, meditation, and sustainable living. We work with certified health professionals to bring you evidence-based advice you can trust.</p><p>Join our community of mindful individuals committed to living their best lives.</p>',
  '<p>Your wellness journey starts here. Reach out to us for guidance, support, or just to say hello.</p><p><strong>Email:</strong> hello@mindfulliving.com</p><p><strong>Wellness Coaching:</strong> coaching@mindfulliving.com</p><p><strong>Meditation Classes:</strong> classes@mindfulliving.com</p><p>Join our newsletter for weekly wellness tips and inspiration.</p>',
  'Find Your Balance',
  'Wellness is a journey, not a destination. Discover practical tips, expert guidance, and gentle inspiration to nurture your body, calm your mind, and elevate your spirit.',
  '<p>Begin your transformation today. Small steps lead to big changes. Subscribe for weekly wellness wisdom delivered to your inbox.</p>',
  5,
  5,
  5,
  5,
  5,
  '#059669',
  '#f0fdf4',
  '#10b981',
  '#ecfdf5',
  '#14532d',
  'sans-serif',
  'serif',
  'max-w-4xl',
  'rounded',
  'https://via.placeholder.com/200x200/059669/ffffff?text=ML',
  'https://via.placeholder.com/32x32/059669/ffffff?text=M',
  'Find balance and peace with our wellness guides, mental health resources, and mindful living tips',
  'https://twitter.com/mindfulliving',
  'https://facebook.com/mindfulliving',
  'https://instagram.com/mindfulliving',
  'https://linkedin.com/company/mindfulliving',
  false,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  true,
  false
);

-- Insert dummy blog posts for TechInsights (localhost)
INSERT INTO blog_post (
  website_id,
  slug,
  title,
  excerpt,
  content,
  image_url,
  author_name,
  author_avatar,
  published,
  published_at,
  tags,
  meta_title,
  meta_description
)
SELECT
  id,
  'future-of-artificial-intelligence',
  'The Future of Artificial Intelligence: What to Expect in 2025',
  'AI is evolving rapidly. Discover the key trends and breakthroughs that will shape artificial intelligence in 2025 and beyond.',
  '<p>Artificial Intelligence has come a long way, and 2025 promises to be a breakthrough year. From generative AI to autonomous systems, the landscape is changing faster than ever.</p><h2>Key Trends to Watch</h2><p>The integration of AI into everyday life is accelerating. We''re seeing advancements in natural language processing, computer vision, and reinforcement learning that were unimaginable just a few years ago.</p><h2>Ethical Considerations</h2><p>As AI becomes more powerful, questions about ethics, privacy, and control become increasingly important. The tech industry must address these concerns head-on.</p><h2>The Road Ahead</h2><p>The future of AI is bright, but it requires careful stewardship. By balancing innovation with responsibility, we can create AI systems that benefit all of humanity.</p>',
  'https://via.placeholder.com/1200x600/2563eb/ffffff?text=AI+Future',
  'Sarah Chen',
  'https://via.placeholder.com/100x100/6366f1/ffffff?text=SC',
  true,
  NOW() - INTERVAL '2 days',
  ARRAY['AI', 'Technology', 'Future'],
  'The Future of Artificial Intelligence in 2025',
  'Explore the key AI trends and breakthroughs expected in 2025'
FROM website_data WHERE host_name = 'localhost';

INSERT INTO blog_post (
  website_id,
  slug,
  title,
  excerpt,
  content,
  image_url,
  author_name,
  author_avatar,
  published,
  published_at,
  tags
)
SELECT
  id,
  'web-development-best-practices',
  'Modern Web Development: Best Practices for 2025',
  'Build faster, more secure, and accessible web applications with these essential best practices for modern web development.',
  '<p>Web development has evolved significantly, and staying current with best practices is crucial for building high-quality applications.</p><h2>Performance First</h2><p>Users expect lightning-fast experiences. Optimize your images, minimize JavaScript, and leverage modern frameworks like Next.js for optimal performance.</p><h2>Accessibility Matters</h2><p>Building accessible websites isn''t just good practice—it''s essential. Use semantic HTML, proper ARIA labels, and ensure keyboard navigation works flawlessly.</p><h2>Security by Design</h2><p>Security can''t be an afterthought. Implement proper authentication, sanitize inputs, and keep your dependencies updated to protect your users.</p>',
  'https://via.placeholder.com/1200x600/7c3aed/ffffff?text=Web+Dev',
  'Marcus Johnson',
  'https://via.placeholder.com/100x100/8b5cf6/ffffff?text=MJ',
  true,
  NOW() - INTERVAL '5 days',
  ARRAY['Web Development', 'Best Practices', 'Tutorial']
FROM website_data WHERE host_name = 'localhost';

INSERT INTO blog_post (
  website_id,
  slug,
  title,
  excerpt,
  content,
  image_url,
  author_name,
  author_avatar,
  published,
  published_at,
  tags
)
SELECT
  id,
  'cybersecurity-threats-2025',
  'Top Cybersecurity Threats to Watch in 2025',
  'Stay ahead of cybercriminals by understanding the emerging security threats that will dominate 2025.',
  '<p>Cybersecurity threats are becoming more sophisticated every year. Here''s what you need to know to protect yourself and your organization.</p><h2>AI-Powered Attacks</h2><p>Cybercriminals are leveraging AI to create more convincing phishing attacks and find vulnerabilities faster than ever before.</p><h2>Ransomware Evolution</h2><p>Ransomware continues to evolve, with attackers targeting critical infrastructure and demanding larger ransoms.</p><h2>Supply Chain Vulnerabilities</h2><p>The software supply chain remains a weak point. Recent attacks have shown how a single compromised dependency can affect thousands of applications.</p><h2>Staying Protected</h2><p>Implement multi-factor authentication, keep systems updated, train employees, and maintain regular backups to minimize risk.</p>',
  'https://via.placeholder.com/1200x600/dc2626/ffffff?text=Cybersecurity',
  'Elena Rodriguez',
  'https://via.placeholder.com/100x100/ef4444/ffffff?text=ER',
  true,
  NOW() - INTERVAL '1 day',
  ARRAY['Cybersecurity', 'Security', 'Threats']
FROM website_data WHERE host_name = 'localhost';

INSERT INTO blog_post (
  website_id,
  slug,
  title,
  excerpt,
  content,
  image_url,
  author_name,
  author_avatar,
  published,
  published_at,
  tags
)
SELECT
  id,
  'cloud-computing-trends',
  'Cloud Computing Trends Reshaping Enterprise IT',
  'Discover how cloud computing innovations are transforming how businesses operate and scale in the digital age.',
  '<p>Cloud computing has become the backbone of modern enterprise IT. Let''s explore the trends that are reshaping the industry.</p><h2>Multi-Cloud Strategies</h2><p>Organizations are moving beyond single-cloud deployments to leverage the strengths of multiple cloud providers.</p><h2>Serverless Architecture</h2><p>Serverless computing allows developers to focus on code without managing infrastructure, leading to faster development cycles and lower costs.</p><h2>Edge Computing</h2><p>Processing data closer to its source reduces latency and bandwidth usage, enabling real-time applications.</p><h2>Green Cloud</h2><p>Sustainability is becoming a priority, with cloud providers investing heavily in renewable energy and carbon-neutral data centers.</p>',
  'https://via.placeholder.com/1200x600/0891b2/ffffff?text=Cloud+Computing',
  'Sarah Chen',
  'https://via.placeholder.com/100x100/6366f1/ffffff?text=SC',
  true,
  NOW() - INTERVAL '7 days',
  ARRAY['Cloud Computing', 'Enterprise', 'Infrastructure']
FROM website_data WHERE host_name = 'localhost';

INSERT INTO blog_post (
  website_id,
  slug,
  title,
  excerpt,
  content,
  image_url,
  author_name,
  author_avatar,
  published,
  published_at,
  tags
)
SELECT
  id,
  'machine-learning-beginners-guide',
  'Machine Learning for Beginners: A Practical Guide',
  'New to machine learning? This comprehensive guide will help you understand the fundamentals and start building your first models.',
  '<p>Machine learning can seem intimidating, but with the right approach, anyone can learn it. This guide will get you started.</p><h2>What is Machine Learning?</h2><p>Machine learning is a subset of AI that enables computers to learn from data without being explicitly programmed.</p><h2>Types of Machine Learning</h2><p>There are three main types: supervised learning, unsupervised learning, and reinforcement learning. Each has its own use cases and applications.</p><h2>Getting Started</h2><p>Begin with Python and libraries like scikit-learn. Start with simple datasets and gradually work your way up to more complex problems.</p><h2>Common Algorithms</h2><p>Linear regression, decision trees, and neural networks are great starting points for learning how different algorithms work.</p>',
  'https://via.placeholder.com/1200x600/10b981/ffffff?text=Machine+Learning',
  'Marcus Johnson',
  'https://via.placeholder.com/100x100/8b5cf6/ffffff?text=MJ',
  true,
  NOW() - INTERVAL '10 days',
  ARRAY['Machine Learning', 'Tutorial', 'Beginners']
FROM website_data WHERE host_name = 'localhost';

INSERT INTO blog_post (
  website_id,
  slug,
  title,
  excerpt,
  content,
  image_url,
  author_name,
  author_avatar,
  published,
  published_at,
  tags
)
SELECT
  id,
  'blockchain-beyond-cryptocurrency',
  'Blockchain Technology Beyond Cryptocurrency',
  'Explore how blockchain is revolutionizing industries beyond crypto, from supply chain to healthcare.',
  '<p>While cryptocurrency grabbed headlines, blockchain technology has far-reaching applications across many industries.</p><h2>Supply Chain Management</h2><p>Blockchain provides transparency and traceability in supply chains, helping companies verify the authenticity of products and prevent fraud.</p><h2>Healthcare Records</h2><p>Secure, decentralized health records give patients control over their data while enabling seamless sharing between healthcare providers.</p><h2>Digital Identity</h2><p>Blockchain-based identity systems can provide secure, portable digital identities that users control.</p><h2>The Future</h2><p>As blockchain matures, we''ll see even more innovative applications emerge across different sectors.</p>',
  'https://via.placeholder.com/1200x600/f59e0b/ffffff?text=Blockchain',
  'Elena Rodriguez',
  'https://via.placeholder.com/100x100/ef4444/ffffff?text=ER',
  true,
  NOW() - INTERVAL '3 days',
  ARRAY['Blockchain', 'Technology', 'Innovation']
FROM website_data WHERE host_name = 'localhost';

-- Insert blog posts for localhost:3000 (same website, different hostname)
INSERT INTO blog_post (
  website_id,
  slug,
  title,
  excerpt,
  content,
  image_url,
  author_name,
  author_avatar,
  published,
  published_at,
  tags
)
SELECT
  id,
  'quantum-computing-explained',
  'Quantum Computing Explained: The Next Computing Revolution',
  'Dive into the fascinating world of quantum computing and understand how it will change technology forever.',
  '<p>Quantum computing represents a paradigm shift in how we process information. Unlike classical computers that use bits, quantum computers use qubits.</p><h2>Understanding Qubits</h2><p>Qubits can exist in multiple states simultaneously thanks to quantum superposition, enabling massive parallel processing.</p><h2>Real-World Applications</h2><p>From drug discovery to cryptography, quantum computers will solve problems currently impossible for classical computers.</p><h2>Challenges Ahead</h2><p>Quantum computers are extremely sensitive to environmental interference and require near-absolute zero temperatures to operate.</p>',
  'https://via.placeholder.com/1200x600/8b5cf6/ffffff?text=Quantum',
  'Dr. Alex Kumar',
  'https://via.placeholder.com/100x100/a855f7/ffffff?text=AK',
  true,
  NOW() - INTERVAL '4 days',
  ARRAY['Quantum Computing', 'Future Tech', 'Science']
FROM website_data WHERE host_name = 'localhost:3000';

-- Insert blog posts for The Foodie Chronicles
INSERT INTO blog_post (
  website_id,
  slug,
  title,
  excerpt,
  content,
  image_url,
  author_name,
  author_avatar,
  published,
  published_at,
  tags
)
SELECT
  id,
  'perfect-homemade-pasta',
  'The Art of Perfect Homemade Pasta: A Complete Guide',
  'Learn the secrets to making restaurant-quality pasta at home with this comprehensive guide.',
  '<p>There''s nothing quite like fresh homemade pasta. The texture, the taste, the satisfaction—it''s incomparable to dried pasta.</p><h2>Essential Ingredients</h2><p>All you need is flour, eggs, salt, and olive oil. The quality of your ingredients directly impacts the final result.</p><h2>The Technique</h2><p>Knead the dough until it''s smooth and elastic, then let it rest. This allows the gluten to relax, making it easier to roll.</p><h2>Rolling and Cutting</h2><p>Whether you use a pasta machine or a rolling pin, aim for even thickness. Cut into your desired shape—fettuccine, tagliatelle, or pappardelle.</p><h2>Cooking Tips</h2><p>Fresh pasta cooks much faster than dried. Use plenty of salted water and taste frequently to achieve perfect al dente texture.</p>',
  'https://via.placeholder.com/1200x600/dc2626/ffffff?text=Pasta',
  'Chef Isabella Romano',
  'https://via.placeholder.com/100x100/f87171/ffffff?text=IR',
  true,
  NOW() - INTERVAL '1 day',
  ARRAY['Recipes', 'Italian', 'Pasta']
FROM website_data WHERE host_name = 'foodie.example.com';

INSERT INTO blog_post (
  website_id,
  slug,
  title,
  excerpt,
  content,
  image_url,
  author_name,
  author_avatar,
  published,
  published_at,
  tags
)
SELECT
  id,
  'japanese-ramen-secrets',
  '5 Secrets to Authentic Japanese Ramen at Home',
  'Discover the techniques Japanese ramen masters use to create that perfect bowl of comfort.',
  '<p>Authentic ramen is an art form that takes years to master, but these secrets will elevate your homemade ramen significantly.</p><h2>The Broth is Everything</h2><p>A rich, flavorful broth is the foundation. Simmer pork bones for 12+ hours to extract maximum flavor and create that creamy tonkotsu base.</p><h2>Perfect Noodles</h2><p>Ramen noodles have a unique texture thanks to kansui (alkaline mineral water). This gives them their characteristic chew and yellow color.</p><h2>The Toppings</h2><p>Chashu pork, soft-boiled eggs, nori, and green onions aren''t just garnishes—they''re essential components that complete the bowl.</p>',
  'https://via.placeholder.com/1200x600/f59e0b/ffffff?text=Ramen',
  'Yuki Tanaka',
  'https://via.placeholder.com/100x100/fbbf24/ffffff?text=YT',
  true,
  NOW() - INTERVAL '3 days',
  ARRAY['Recipes', 'Japanese', 'Ramen']
FROM website_data WHERE host_name = 'foodie.example.com';

-- Insert blog posts for Wanderlust Diaries
INSERT INTO blog_post (
  website_id,
  slug,
  title,
  excerpt,
  content,
  image_url,
  author_name,
  author_avatar,
  published,
  published_at,
  tags
)
SELECT
  id,
  'hidden-gems-italy',
  'Hidden Gems of Italy: Beyond Rome and Venice',
  'Discover the lesser-known Italian towns that offer authentic experiences away from tourist crowds.',
  '<p>Italy has so much more to offer beyond its famous cities. These hidden gems provide authentic Italian experiences without the crowds.</p><h2>Matera</h2><p>This ancient city carved into rock is one of the world''s oldest continuously inhabited settlements. Its sassi (cave dwellings) are now boutique hotels and restaurants.</p><h2>Cinque Terre</h2><p>Five colorful fishing villages perched on cliffs overlooking the Mediterranean. Connected by scenic hiking trails with breathtaking views.</p><h2>Bologna</h2><p>Known as "La Grassa" (the fat one) for its incredible cuisine. The city offers amazing food, beautiful arcades, and medieval towers.</p>',
  'https://via.placeholder.com/1200x600/0891b2/ffffff?text=Italy',
  'Sofia Martinez',
  'https://via.placeholder.com/100x100/06b6d4/ffffff?text=SM',
  true,
  NOW() - INTERVAL '2 days',
  ARRAY['Italy', 'Europe', 'Hidden Gems']
FROM website_data WHERE host_name = 'travel.example.com';

-- Insert blog posts for Mindful Living
INSERT INTO blog_post (
  website_id,
  slug,
  title,
  excerpt,
  content,
  image_url,
  author_name,
  author_avatar,
  published,
  published_at,
  tags
)
SELECT
  id,
  'meditation-beginners-guide',
  'Meditation for Beginners: Start Your Practice Today',
  'A simple, practical guide to starting your meditation practice and experiencing its life-changing benefits.',
  '<p>Meditation isn''t about stopping your thoughts—it''s about changing your relationship with them. Here''s how to begin.</p><h2>Start Small</h2><p>Begin with just 5 minutes a day. Consistency matters more than duration when building a meditation habit.</p><h2>Find Your Space</h2><p>Choose a quiet, comfortable spot where you won''t be disturbed. Make it inviting with cushions, candles, or plants.</p><h2>Focus on Breathing</h2><p>Your breath is your anchor. When your mind wanders (and it will), gently bring your attention back to your breathing.</p><h2>Be Patient</h2><p>Meditation is a practice. Some days will feel easier than others, and that''s perfectly normal.</p>',
  'https://via.placeholder.com/1200x600/059669/ffffff?text=Meditation',
  'Dr. Maya Patel',
  'https://via.placeholder.com/100x100/10b981/ffffff?text=MP',
  true,
  NOW() - INTERVAL '1 day',
  ARRAY['Meditation', 'Mindfulness', 'Wellness']
FROM website_data WHERE host_name = 'wellness.example.com';

-- Success message
SELECT 'Database seeded successfully!' as message;
SELECT 'Websites created: ' || COUNT(*) as websites FROM website_data;
SELECT 'Blog posts created: ' || COUNT(*) as blog_posts FROM blog_post;
